# url: https://okowe.github.io/
# baseurl: ""

# Site settings
title: OKO WE
email: helene@okowe.fr
description: C’est en partageant qu’on créera le monde !


# Team names, titles and social links
people:
- name: Helene
  pic: 1
  position: Lead Designer

- name: Larry Parker
  pic: 2
  position: Lead Marketer

- name: Diana Petersen
  pic: 3
  position: Lead Developer

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
